### ISSUE TITLE
fix: minor documentation updates

### ISSUE THREAD

**Issue by nahueloyha** [stratosnet/stratos-doc#2]
Ey there, kudos for the great docs! I just went through the full-chain & validator setup and spotted a few minor details which I'm reporting here... 

I'm happy to fix them myself in a PR but couldn't find the updated version of the docs in this repo, as the [published docs](https://docs.thestratos.org/docs-stratos-chain/how-to-become-a-validator/) doesn't seem to match the committed ones here (in neither the raw `main` branch nor the mkdocs-generated `gh-pages` one).

1. The path for stchaind binary in the service definition is not accurate as it was previously moved to ~/bin: 

```
[Service]
User=stratos
ExecStart=/home/stratos/stchaind start --home=/home/stratos/.stchaind
```

2. The expect md5sum output for the v0.11.3 didn't match, I got `0d4a0fd5173fa273f6150b28e48086a3`

```
## Expected output
## c3e55667fd2eb0a345dde80a56068a6a  stchaind
```

3. In the "#### Pre-compiled executables" section, the stchain version could be updated to the recently released v0.11.4:

```
# Make sure we are inside the $HOME folder
cd $HOME
wget https://github.com/stratosnet/stratos-chain/releases/download/v0.11.3/stchaind
```

4. In the "## Create a new validator" section, some fields are missing to fully match the example with the explanation:

```
- Missing in the example:

website: website(Optional)
description: description(Optional)

- Missing in the explanation: 

--amount=100stos \
--from=st1dz20dmhjkuc2tur3amgl8t45w807a640leh8p0 \
--gas=auto \
--gas-adjustment=1.5 \
--gas-prices=1000000000wei -y
```

**Comment by alexstratos** [comment]
Hi Nahuel, 

Thanks for the report, please check the most updated document at https://github.com/stratosnet/stratosnet.github.io

we are maintaining the docu site https://docs.thestratos.org/ from that repo.

**Comment by alexstratos** [comment]
I addressed most of your suggestion, but left over the 3rd one, as there might be some problem if people start the chain from genesis using v0.11.4 without using state sync.  https://github.com/stratosnet/stratosnet.github.io/pull/43

**Comment by nahueloyha** [comment]
Awesome, thanks @alexstratos ! Maybe this repo can be archived if not used anymore to avoid future confusion 😅
